version: '3.2'
services:
  elk:
    image: sebp/elk:latest
    environment:
     - LOGSTASH_START=0
     - KIBANA_START=1
     - ELASTICSEARCH_START=1
     - TZ=Asia/Seoul
     - ES_HEAP_SIZE=1g
     - LS_HEAP_SIZE=2g
    ports:
     - 5601:5601
     - 9200:9200
     - 5000:5000
    volumes:
     - elk-data:/var/lib/elasticsearch 
volumes:
 elk-data:
    external: true
